openapi: 3.0.0
info:  
  title: DIRECTORATE OF SKILL DEVELOPMENT, Madhya Pradesh
  description: The Department of Skill Development (DSD), Government of Madhya Pradesh, is responsible for the overall development and the basic structure of Skill development initiative across the state. It covers policymaking, planning and implementation. Under a planned process, DSD looks after the expansion and qualitative improvement in skill development, through different initiatives.
  termsOfService: https://apisetu.gov.in/terms.php
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/mp'
paths:
  /iticr:
    post:
      tags:
        - APIs
      summary: ITI Certificate
      description: API to verify ITI Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: iticr
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                certificateParameters:
                  type: object
                  required:
                    - RollNumber
                    - PassYear
                    - FullName
                    - DOB
                    - GENDER
  
                  properties:
                    RollNumber:
                      type: string
                      description: Roll Number
                      example: "11a12345678"
                    PassYear:
                      type: string
                      description: Passing Year
                      example: "2019"
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"
                    GENDER:
                      type: string
                      description: Gender - M for male, F for female and O for other
                      example: "M"
  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
  /skmst:
    post:
      tags:
        - APIs
      summary: Skill Marksheet/ Score Card
      description: API to verify Skill Marksheet/ Score Card.
      security:
        - clientId: []
          apiKey: []
      operationId: skmst
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                certificateParameters:
                  type: object
                  required:
                    - RollNumber
                    - PassYear
                    - FullName
                    - DOB
                    - GENDER
  
                  properties:
                    RollNumber:
                      type: string
                      description: Roll Number
                      example: "11a12345678"
                    PassYear:
                      type: string
                      description: Passing Year
                      example: "2019"
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"
                    DOB:
                      type: string
                      description: Date of birth in DD-MM-YYYY format
                      example: "31-12-1980"
                    GENDER:
                      type: string
                      description: Gender - M for male, F for female and O for other
                      example: "M"
  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
      
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY