openapi: 3.0.0
info:  
  title: Madhya Pradesh Medical Council, Madhya Pradesh
  description: APIs provided by Madhya Pradesh Medical Council, Madhya Pradesh.
  termsOfService: https://apisetu.gov.in/terms.php
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/mpmc'
paths:
  /socer:
    post:
      tags:
        - APIs
      summary: Educational/ Exam Registration Certificate
      description: API to verify Educational/ Exam Registration Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: socer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                certificateParameters:
                  type: object
                  required:
                    - CertificateType
                    - ApplicantName
                    - DOB
                    - RegNo
                    - RegDate
  
                  properties:
                    CertificateType:
                      type: string
                      description: Type Of Certificate
                      example: "Permanent,Additional,Duplicate Permanent,Duplicate Additional"
                    ApplicantName:
                      type: string
                      description: Applicant Name
                      example: "Same As Given In Certificate"
                    DOB:
                      type: string
                      description: Date Of Birth
                      example: "DD/MM/YYYY"
                    RegNo:
                      type: string
                      description: Registration Number
                      example: "Same As Given In Certificate"
                    RegDate:
                      type: string
                      description: Registration Date
                      example: "DD/MM/YYYY"
  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
      
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY