openapi: 3.0.0
info:  
  title: Paramedical Council, Madhya Pradesh
  description: Registration Certificate, Duplicate Registration Certificate, Good Standing Certificate, Registration Renewal, Tatkal Registration, Tatkal  Registration Renewal and Upadhi/Certificate as issued by MP Paramedical Council (http://www.mppmc.ac.in) from April 2017 onwards can be pulled into citizens' DigiLocker accounts. 
  termsOfService: https://apisetu.gov.in/terms.php
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/mppmc'
paths:
  /socer:
    post:
      tags:
        - APIs
      summary: Educational/ Exam Registration Certificate
      description: API to verify Educational/ Exam Registration Certificate.
      security:
        - clientId: []
          apiKey: []
      operationId: socer
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                    - pdf
                certificateParameters:
                  type: object
                  required:
                    - APPNO
                    - TypOfCert
                    - ENROLNO
                    - Date_Of_Birth
  
                  properties:
                    APPNO:
                      type: string
                      description: Registration Application No
                      example: "REG1307241"
                    TypOfCert:
                      type: string
                      description: Type Of Service
                      example: "Registration Certificate&#x28;PREGC&#x29;,Duplicate Registration Certificate&#x28;PDURC&#x29;,Good S"
                    ENROLNO:
                      type: string
                      description: Enrollment No.
                      example: "41C172C17OCT1203"
                    Date_Of_Birth:
                      type: string
                      description: Date Of Birth
                      example: "11-11-1990"
  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
            application/pdf:
              example: Response body contains contents of the certificate in PDF format.
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
      
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY