openapi: 3.0.0
info:  
  title: National Testing Agency (NTA)
  description: National Testing Agency (NTA) (http://nta.ac.in) is issuing JEE MAINS Scorecards through DigiLocker. These can be pulled by students into their DigiLocker accounts. Currently, data for the year 2020 is made available by NTA.
  termsOfService: https://apisetu.gov.in/terms.php
  version: 3.0.0
servers:
  - url: 'https://apisetu.gov.in/certificate/v3/nta'
paths:
  /ntmst:
    post:
      tags:
        - APIs
      summary: NTA Marksheet
      description: API to verify NTA Marksheet.
      security:
        - clientId: []
          apiKey: []
      operationId: ntmst
      requestBody:
        description: Request format
        content:
          application/json:
            schema:
              type: object
              required:
                - txnId
                - format
              properties:
                txnId:
                  type: string
                  format: uuid
                  description: A unique transaction id for this request in UUID format. It is used for tracking the request.
                  example: "f7f1469c-29b0-4325-9dfc-c567200a70f7"
                format:
                  type: string
                  description: The format of the certificate in response.
                  enum:
                certificateParameters:
                  type: object
                  required:
                    - APPNO
                    - YEAR
                    - PAPER_NO
                    - FullName
  
                  properties:
                    APPNO:
                      type: string
                      description: Application No
                      example: "29887710"
                    YEAR:
                      type: string
                      description: Year
                      example: "2020"
                    PAPER_NO:
                      type: string
                      description: Paper No
                      example: "PAPER-1,PAPER-2"
                    FullName:
                      type: string
                      description: Full name
                      example: "Sunil Kumar"
  
                consentArtifact:
                  $ref: '#/components/schemas/ConsentArtifactSchema'
      responses:
        '200':
          description: The certificate data in response body in PDF, XML or JSON format as requested in format parameter.
          content:
        '400':
          $ref: '#/components/responses/400Error'
        '401':
          $ref: '#/components/responses/401Error'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'
        '502':
          $ref: '#/components/responses/502Error'
        '503':
          $ref: '#/components/responses/503Error'
        '504':
          $ref: '#/components/responses/504Error'
components:
  schemas:
    ConsentArtifactSchema:
      $ref: './common/ConsentArtifactSchema.yaml#/ConsentArtifactSchema'
    AcademicCertificateSchema:
      $ref: './common/AcademicCertificateSchema.yaml#/AcademicCertificateSchema'
      
  responses:
    400Error:
      $ref: './common/ErrorResponse.yaml#/400Error'
    401Error:
      $ref: './common/ErrorResponse.yaml#/401Error'
    404Error:
      $ref: './common/ErrorResponse.yaml#/404Error'
    500Error:
      $ref: './common/ErrorResponse.yaml#/500Error'
    502Error:
      $ref: './common/ErrorResponse.yaml#/502Error'
    503Error:
      $ref: './common/ErrorResponse.yaml#/503Error'
    504Error:
      $ref: './common/ErrorResponse.yaml#/504Error'
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: X-APISETU-CLIENTID
    apiKey:
      type: apiKey
      in: header
      name: X-APISETU-APIKEY